# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fe3ff266-f363-4765-9acc-98736ae44adc";
      fsType = "btrfs";
      # compress=zstd: reduces NVMe I/O and page-cache pressure (lower OOM risk).
      # noatime: eliminates write-on-read overhead for all file access.
      options = [ "compress=zstd" "noatime" ];
    };

  boot.initrd.luks.devices."luks-fe3ff266-f363-4765-9acc-98736ae44adc".device = "/dev/disk/by-uuid/fe3ff266-f363-4765-9acc-98736ae44adc";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-fe3ff266-f363-4765-9acc-98736ae44adc";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-fe3ff266-f363-4765-9acc-98736ae44adc";
      fsType = "btrfs";
      # noatime is especially impactful on /nix — the store has millions of reads.
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CF6E-18E0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8975b560-92f4-4180-b5cd-d1e03ad2b58b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
